services:
    app:
        build:
            context: ./
            dockerfile: .docker/8.2/Dockerfile
        volumes:
            - '.:/var/www/html'
        networks:
            - backend
    worker:
        build:
            context: ./
            dockerfile: .docker/8.2/Dockerfile
        volumes:
            - '.:/var/www/html'
        networks:
            - backend
networks:
    backend:
        driver: bridge
